branch-defaults:
  lw-devel:
    environment: LessestWrong
  ea-dev:
    environment: GF-Forum-Staging
global:
  # Use deploy.sh to change this to the correct application name
  application_name: GF-Forum
  branch: null
  default_platform: Docker
  default_region: us-west-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
  workspace_type: Application
